


/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData V1.1                                    /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

    
  $data.Entity.extend('Crm.EntityReference', {
     'Id': { 'type':'Edm.Guid','nullable':true },
     'LogicalName': { 'type':'Edm.String','nullable':true },
     'Name': { 'type':'Edm.String','nullable':true }
  });

  $data.Entity.extend('Crm.OptionSetValue', {
     'Value': { 'type':'Edm.Int32','nullable':true }
  });

  $data.Entity.extend('Crm.Money', {
     'Value': { 'type':'Edm.Decimal','nullable':true }
  });

  $data.Entity.extend('Crm.BooleanManagedProperty', {
     'Value': { 'type':'Edm.Boolean','nullable':true },
     'CanBeChanged': { 'type':'Edm.Boolean','nullable':true },
     'ManagedPropertyLogicalName': { 'type':'Edm.String','nullable':true }
  });

  $data.Entity.extend('Crm.new_expenseclaimitem', {
     'OwningUser': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'OverriddenCreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'ModifiedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'ModifiedOn': { 'type':'Edm.DateTime','nullable':true },
     'ImportSequenceNumber': { 'type':'Edm.Int32','nullable':true },
     'statecode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'OwningTeam': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'OwnerId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'CreatedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'UTCConversionTimeZoneCode': { 'type':'Edm.Int32','nullable':true },
     'statuscode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'ModifiedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'new_name': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
     'TimeZoneRuleVersionNumber': { 'type':'Edm.Int32','nullable':true },
     'VersionNumber': { 'type':'Edm.Int64','nullable':true },
     'new_ExpenseClaimId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'new_expenseclaimitemId': { 'key':true,'type':'Edm.Guid','nullable':false,'required':true },
     'OwningBusinessUnit': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'new_Amount': { 'type':'Edm.Double','nullable':true },
     'CreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'CreatedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'new_expenseclaimitem_Annotations': { 'type':'Array','elementType':'Crm.Annotation','inverseProperty':'new_expenseclaimitem_Annotations' },
     'new_claimitems': { 'type':'Crm.new_expenseclaim','inverseProperty':'new_claimitems' }
  });

  $data.Entity.extend('Crm.Annotation', {
     'ModifiedOn': { 'type':'Edm.DateTime','nullable':true },
     'ImportSequenceNumber': { 'type':'Edm.Int32','nullable':true },
     'FileSize': { 'type':'Edm.Int32','nullable':true },
     'OverriddenCreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'ModifiedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'ObjectTypeCode': { 'type':'Edm.String','nullable':true },
     'CreatedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'MimeType': { 'type':'Edm.String','nullable':true },
     'ModifiedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'DocumentBody': { 'type':'Edm.String','nullable':true },
     'OwningTeam': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'VersionNumber': { 'type':'Edm.Int64','nullable':true },
     'Subject': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
     'NoteText': { 'type':'Edm.String','nullable':true },
     'OwningUser': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'AnnotationId': { 'key':true,'type':'Edm.Guid','nullable':false,'required':true },
     'CreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'StepId': { 'type':'Edm.String','nullable':true },
     'FileName': { 'type':'Edm.String','nullable':true },
     'LangId': { 'type':'Edm.String','nullable':true },
     'OwningBusinessUnit': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'OwnerId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'ObjectId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'IsDocument': { 'type':'Edm.Boolean','nullable':true },
     'CreatedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'Lead_Annotation': { 'type':'Crm.Lead','inverseProperty':'Lead_Annotation' },
     'new_expenseclaim_Annotations': { 'type':'Crm.new_expenseclaim','inverseProperty':'new_expenseclaim_Annotations' },
     'new_expenseclaimitem_Annotations': { 'type':'Crm.new_expenseclaimitem','inverseProperty':'new_expenseclaimitem_Annotations' }
  });

  $data.Entity.extend('Crm.Lead', {
     'Address1_Name': { 'type':'Edm.String','nullable':true },
     'ContactId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'Address1_Telephone2': { 'type':'Edm.String','nullable':true },
     'LastName': { 'type':'Edm.String','nullable':true },
     'Address1_City': { 'type':'Edm.String','nullable':true },
     'Address1_Telephone1': { 'type':'Edm.String','nullable':true },
     'UTCConversionTimeZoneCode': { 'type':'Edm.Int32','nullable':true },
     'Address2_Country': { 'type':'Edm.String','nullable':true },
     'Address2_Latitude': { 'type':'Edm.Double','nullable':true },
     'ModifiedOn': { 'type':'Edm.DateTime','nullable':true },
     'Address2_City': { 'type':'Edm.String','nullable':true },
     'BudgetAmount_Base': { 'type':'Crm.Money','nullable':false,'required':true },
     'EstimatedValue': { 'type':'Edm.Double','nullable':true },
     'LastUsedInCampaign': { 'type':'Edm.DateTime','nullable':true },
     'Address1_County': { 'type':'Edm.String','nullable':true },
     'BudgetStatus': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'ModifiedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'CampaignId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'Address1_Line3': { 'type':'Edm.String','nullable':true },
     'DoNotBulkEMail': { 'type':'Edm.Boolean','nullable':true },
     'StateCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'EstimatedCloseDate': { 'type':'Edm.DateTime','nullable':true },
     'Address2_AddressTypeCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'LeadSourceCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'SalesStage': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'InitialCommunication': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'Address2_ShippingMethodCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'EstimatedAmount_Base': { 'type':'Crm.Money','nullable':false,'required':true },
     'BudgetAmount': { 'type':'Crm.Money','nullable':false,'required':true },
     'Telephone1': { 'type':'Edm.String','nullable':true },
     'IndustryCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'Telephone3': { 'type':'Edm.String','nullable':true },
     'Address1_Country': { 'type':'Edm.String','nullable':true },
     'MiddleName': { 'type':'Edm.String','nullable':true },
     'CustomerId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'ExchangeRate': { 'type':'Edm.Decimal','nullable':true },
     'OverriddenCreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'MobilePhone': { 'type':'Edm.String','nullable':true },
     'Fax': { 'type':'Edm.String','nullable':true },
     'ParticipatesInWorkflow': { 'type':'Edm.Boolean','nullable':true },
     'CreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'AccountId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'SIC': { 'type':'Edm.String','nullable':true },
     'Subject': { 'type':'Edm.String','nullable':true },
     'YomiFullName': { 'type':'Edm.String','nullable':true },
     'Address1_UPSZone': { 'type':'Edm.String','nullable':true },
     'CreatedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'MasterId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'ParentContactId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'YomiFirstName': { 'type':'Edm.String','nullable':true },
     'Address1_StateOrProvince': { 'type':'Edm.String','nullable':true },
     'EMailAddress2': { 'type':'Edm.String','nullable':true },
     'Address1_PostOfficeBox': { 'type':'Edm.String','nullable':true },
     'DoNotFax': { 'type':'Edm.Boolean','nullable':true },
     'VersionNumber': { 'type':'Edm.Int64','nullable':true },
     'Address2_County': { 'type':'Edm.String','nullable':true },
     'Address2_Line3': { 'type':'Edm.String','nullable':true },
     'Address2_Line1': { 'type':'Edm.String','nullable':true },
     'Address1_Line1': { 'type':'Edm.String','nullable':true },
     'NumberOfEmployees': { 'type':'Edm.Int32','nullable':true },
     'CompanyName': { 'type':'Edm.String','nullable':true },
     'FullName': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
     'QualifyingOpportunityId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'Need': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'Address2_Longitude': { 'type':'Edm.Double','nullable':true },
     'FirstName': { 'type':'Edm.String','nullable':true },
     'Address1_Latitude': { 'type':'Edm.Double','nullable':true },
     'ScheduleFollowUp_Qualify': { 'type':'Edm.DateTime','nullable':true },
     'DecisionMaker': { 'type':'Edm.Boolean','nullable':true },
     'Address2_Fax': { 'type':'Edm.String','nullable':true },
     'Telephone2': { 'type':'Edm.String','nullable':true },
     'Address2_Telephone1': { 'type':'Edm.String','nullable':true },
     'Address2_UPSZone': { 'type':'Edm.String','nullable':true },
     'Address1_Telephone3': { 'type':'Edm.String','nullable':true },
     'PurchaseTimeFrame': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'PreferredContactMethodCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'Address2_Line2': { 'type':'Edm.String','nullable':true },
     'OwnerId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'WebSiteUrl': { 'type':'Edm.String','nullable':true },
     'Address2_PostalCode': { 'type':'Edm.String','nullable':true },
     'Address1_ShippingMethodCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'OwningUser': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'ScheduleFollowUp_Prospect': { 'type':'Edm.DateTime','nullable':true },
     'LeadQualityCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'Address2_AddressId': { 'type':'Edm.Guid','nullable':true },
     'Pager': { 'type':'Edm.String','nullable':true },
     'DoNotSendMM': { 'type':'Edm.Boolean','nullable':true },
     'Address2_Name': { 'type':'Edm.String','nullable':true },
     'OwningBusinessUnit': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'CreatedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'Address1_AddressId': { 'type':'Edm.Guid','nullable':true },
     'Address2_Telephone2': { 'type':'Edm.String','nullable':true },
     'Address1_Fax': { 'type':'Edm.String','nullable':true },
     'Salutation': { 'type':'Edm.String','nullable':true },
     'DoNotEMail': { 'type':'Edm.Boolean','nullable':true },
     'YomiMiddleName': { 'type':'Edm.String','nullable':true },
     'TimeZoneRuleVersionNumber': { 'type':'Edm.Int32','nullable':true },
     'SalesStageCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'Address1_PostalCode': { 'type':'Edm.String','nullable':true },
     'PriorityCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'EMailAddress3': { 'type':'Edm.String','nullable':true },
     'StatusCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'YomiLastName': { 'type':'Edm.String','nullable':true },
     'ModifiedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'Address1_UTCOffset': { 'type':'Edm.Int32','nullable':true },
     'TransactionCurrencyId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'QualificationComments': { 'type':'Edm.String','nullable':true },
     'EMailAddress1': { 'type':'Edm.String','nullable':true },
     'Revenue': { 'type':'Crm.Money','nullable':false,'required':true },
     'Merged': { 'type':'Edm.Boolean','nullable':true },
     'DoNotPhone': { 'type':'Edm.Boolean','nullable':true },
     'Address2_StateOrProvince': { 'type':'Edm.String','nullable':true },
     'Address1_Longitude': { 'type':'Edm.Double','nullable':true },
     'OwningTeam': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'EvaluateFit': { 'type':'Edm.Boolean','nullable':true },
     'Address1_AddressTypeCode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'Description': { 'type':'Edm.String','nullable':true },
     'Address2_PostOfficeBox': { 'type':'Edm.String','nullable':true },
     'PurchaseProcess': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'DoNotPostalMail': { 'type':'Edm.Boolean','nullable':true },
     'Address2_UTCOffset': { 'type':'Edm.Int32','nullable':true },
     'EstimatedAmount': { 'type':'Crm.Money','nullable':false,'required':true },
     'LeadId': { 'key':true,'type':'Edm.Guid','nullable':false,'required':true },
     'YomiCompanyName': { 'type':'Edm.String','nullable':true },
     'Address2_Telephone3': { 'type':'Edm.String','nullable':true },
     'ParentAccountId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'Address1_Line2': { 'type':'Edm.String','nullable':true },
     'JobTitle': { 'type':'Edm.String','nullable':true },
     'ConfirmInterest': { 'type':'Edm.Boolean','nullable':true },
     'ImportSequenceNumber': { 'type':'Edm.Int32','nullable':true },
     'Revenue_Base': { 'type':'Crm.Money','nullable':false,'required':true },
     'Referencinglead_master_lead': { 'type':'Crm.Lead','inverseProperty':'Referencedlead_master_lead' },
     'Referencedlead_master_lead': { 'type':'Array','elementType':'Crm.Lead','inverseProperty':'Referencinglead_master_lead' },
     'Lead_Annotation': { 'type':'Array','elementType':'Crm.Annotation','inverseProperty':'Lead_Annotation' },
     'new_expenseclaims': { 'type': 'Array', 'elementType': 'Crm.new_expenseclaim', 'inverseProperty': 'new_expenseclaims' }
  });

  $data.Entity.extend('Crm.new_expenseclaim', {
     'new_expenseclaimId': { 'key':true,'type':'Edm.Guid','nullable':false,'required':true },
     'OwningUser': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'VersionNumber': { 'type':'Edm.Int64','nullable':true },
     'ModifiedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'statecode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'new_ClaimDate': { 'type':'Edm.DateTime','nullable':true },
     'OverriddenCreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'statuscode': { 'type':'Crm.OptionSetValue','nullable':false,'required':true },
     'CreatedOn': { 'type':'Edm.DateTime','nullable':true },
     'ModifiedOn': { 'type':'Edm.DateTime','nullable':true },
     'CreatedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'new_name': { 'type':'Edm.String','nullable':true,'$FC_TargetPath':'SyndicationTitle','$FC_ContentKind':'text','$FC_KeepInContent':'true' },
     'TimeZoneRuleVersionNumber': { 'type':'Edm.Int32','nullable':true },
     'UTCConversionTimeZoneCode': { 'type':'Edm.Int32','nullable':true },
     'ModifiedBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'CreatedOnBehalfBy': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'OwnerId': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'OwningTeam': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'ImportSequenceNumber': { 'type':'Edm.Int32','nullable':true },
     'OwningBusinessUnit': { 'type':'Crm.EntityReference','nullable':false,'required':true },
     'new_expenseclaim_Annotations': { 'type':'Array','elementType':'Crm.Annotation','inverseProperty':'new_expenseclaim_Annotations' },
     'new_claimitems': { 'type': 'Array', 'elementType': 'Crm.new_expenseclaimitem', 'inverseProperty': 'new_claimitems' },
     'new_expenseclaims': { 'type': 'Crm.Lead', 'inverseProperty': 'new_expenseclaims' }

  });

  $data.EntityContext.extend('Crm.DataContext', {
     'new_expenseclaimitemSet': { type: $data.EntitySet, elementType: Crm.new_expenseclaimitem},
     'AnnotationSet': { type: $data.EntitySet, elementType: Crm.Annotation},
     'LeadSet': { type: $data.EntitySet, elementType: Crm.Lead},
     'new_expenseclaimSet': { type: $data.EntitySet, elementType: Crm.new_expenseclaim}
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(Crm.DataContext);
  
      
})(window, $data);
      
    